<div><img src="https://raw.githubusercontent.com/natep514/Homework/main/Images/savvy%20coders%20logo.jpg" style="height:35px;object-fit:cover;"></div>

___
# 4 Python Homework
___

<div><img src="https://raw.githubusercontent.com/natep514/Homework/main/Images/cat2.gif" style="height:px;object-fit:cover;"></div>

___


1. **What does one need to do to use a module?**
    * You have to import the module. </br>
2. **Name a Module (not the DateTime Nodule) we looked at and write a line or 2 of code as an example using this module.**
    * Random
``` py
import random

rps = random.randrange(1,4)
if rps == 1 :
    print('Scissors')
elif rps == 2 :
    print('Rock')
else :
    print('Paper')
```    
3. **What is a benefit of using Exception handling?**
    * Will allow code to run even if an error or exception occurs.
4. **NumPy arrays are like what Python data type?**
    * Lists
5. **What is one of the main benefits of using NumPy arrays.**
    * Uses less memory.
6. **What is one of the main requirements about the 'dtype' of NumPy arrays?**
    * Has to be the same data type.
7. **Of the 10 uses of NumPy, name 2.**
    * Copying & viewing arrays and Mathematic operations.
8. **Name one of the other libraries we'll use with NumPy?**
    * Pandas
9.  **What is the shape of NumPy arrays?**
    * Multidimensional unless it's a vector.
10. **What is a Tensor?**
    * An array with 3+ dimensions
11. **Name a reason why it's better using NumPy for Data Analysis than using a Python List?**
    * Numpy is faster than Python Lists
12. **When creating an "empty" array, where do the elements come from?**
    * Initially it's random and depends on the state of the memory.
___

<div
class="alert alert-info">"Data analytics is the future, and the future is NOW! Every mouse click, keyboard button press, swipe or tap is used to shape business decisions. Everything is about data these days. Data is information, and information is power.”
~ Radi, data analyst at CENTOGENE</div>

In [2]:
'''
Use the DateTime module to get Current Date and Time, and save it to a variable. 
Then extract just the Full month name form that variable.
'''

import datetime as dt

currentdt = dt.datetime.now()
print(currentdt.strftime("%B"))



February


In [1]:
''' 
Write a simple function that takes 2 parameters -- a first name and a day name.

Set a default value for the day name of Sunday.
Have the function print out a greeting -- using the parameters -- that says something like 
"Hi first-name! Happy day-name!". 
Remember to use the variables in the greeting to replace first-name and day-name.
Invoke this function with 2 variables.
Invoke this function with 1 variable only.
'''

import datetime as dt
current = dt.datetime.now()

def nameday(name,day = "Sunday"):
    print("Hi,", name,"! Happy", day, "!")
    
nameday("Nate", "Friday")
nameday("Nate")

# nameday("Nate", current.strftime("%A"))





Hi, Nate ! Happy Friday !
Hi, Nate ! Happy Sunday !


In [2]:
'''
Import NumPy, use one of the NumPy methods and create an array with a shape of ... (2, 3, 2). 
You can use the reshape method -- .reshape()
'''

import numpy as np

a_3d = np.arange(12).reshape((2, 3, 2))
print("Array dimensions / axes ...", a_3d.ndim)
print(a_3d)


Array dimensions / axes ... 3
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [4]:
# Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20

import numpy as np

spaced = np.linspace(0, 20, num=6)
print(spaced)


[ 0.  4.  8. 12. 16. 20.]


In [5]:
# Make a Deep Copy of the above array you created.

import copy

spaced1 = copy.deepcopy(spaced)


* What are 2 reasons we use NumPy arrays over Python Lists?
    * Less memory and faster.
___
<div><img src="https://raw.githubusercontent.com/natep514/Homework/main/Images/savvy%20coders%20logo.jpg" style="height:35px;object-fit:cover;"></div>