<div><img src="https://raw.githubusercontent.com/natep514/Homework/main/Images/savvy%20coders%20logo.jpg" style="height:35px;object-fit:cover;"></div>

___
# 5 Python Homework
___

<div><img src="https://raw.githubusercontent.com/natep514/Homework/main/Images/cat4.gif" style="height:px;object-fit:cover;"></div>

___

1. What does Pandas stand for?
    * Python Data Analysis Library.  Derived from the term "Panel Data".
2. What are the 2 collections used in Pandas?
    * Series and Dataframes
3. Name 4 things Pandas can do for us.
    * Data Cleaning, Data Fill, Loading and Saving Data, and Data Inspection
4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?
    * `inplace=True`
5. What is a CSV
    * Comma Seperated Value file
6. When cleaning data what values do we not like in our data?
    * Null


In [28]:
# Concatenate these 3 arrays into a new array named 'newArray'...
import numpy as np

ax = np.array([[25, 16]])
ay = np.array([[11, 2], [13, 4]])
az = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((ax, ay, az))

# Sort 'newArray' in order into 'sortedArray'
sortedArray = np.sort(newArray)

# Reshape the 'sortedArray' array, into a new array called 'reshapedArray', 
# so it has 2 dimensions with a size of 2, 3.
reshapedArray = np.reshape(sortedArray,(2, 2, 3))
print(reshapedArray)

# Unpack the array tuples from the above 'reshapedArray'  into 4 well named variables. 
# Print the 4 variables.
a, b= reshapedArray
a0, a1 = a
b0, b1 = b
print(a0, a1, b0, b1)

# Combined and sort the following arrays into one called 'comboArray' ...
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.sort(np.concatenate((one, two, three)))

# Take 'comboArray' and perform the following slicing activities:
# print sec1 - the 2nd element
print(comboArray[1])
# print sec2 - all elements from the 3rd element to the last
print(comboArray[2:])
# print sec3 - all elements from the 4th to the 14th elements
print(comboArray[3:15])
# print sec4 - the last 6 elements
print(comboArray[-6:])
# print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
print(comboArray[:-10])    
# print sec6 - from #20 every even element to the end
print(comboArray[16::2])
# print sec7 - from the last element moving forward, every 5th element.
print(comboArray[-1::-5])

[[[16 25  2]
  [11  4 13]]

 [[ 7 81  5]
  [ 6 11 12]]]
[16 25  2] [11  4 13] [ 7 81  5] [ 6 11 12]
1
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14 15 16]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[20 22 24 26]
[27 22 15 10  3]


In [7]:
#Using simple math operations, broadcast the addition `(+)`, division `(/)`, and multiplication `(*)` operations for these 2 arrays --
import numpy as np

a1 = np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
       [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

a2 = np.array([[17.0, 70.0, 10.7]])

print(a1 + a2)
print(a1 / a2)
print(a1 * a2)


# Use the NumPy Arithmetic functions to do the subtraction of the above two arrays in point #7.
print(np.subtract(a1, a2))

# Using modulo find all elements that are divisible by 3 from the multi-dimensional array under point #7 above.
print(a1[a1 % 3 == 0])

[[[ 17.    70.    10.8 ]
  [ 27.    80.3   20.71]]

 [[ 37.    90.02  30.8 ]
  [ 47.   101.    41.  ]]

 [[ 57.4   94.    50.7 ]
  [ 32.    85.5   36.2 ]]]
[[[0.         0.         0.00934579]
  [0.58823529 0.14714286 0.93551402]]

 [[1.17647059 0.286      1.87850467]
  [1.76470588 0.44285714 2.8317757 ]]

 [[2.37647059 0.34285714 3.73831776]
  [0.88235294 0.22142857 2.38317757]]]
[[[0.00000e+00 0.00000e+00 1.07000e+00]
  [1.70000e+02 7.21000e+02 1.07107e+02]]

 [[3.40000e+02 1.40140e+03 2.15070e+02]
  [5.10000e+02 2.17000e+03 3.24210e+02]]

 [[6.86800e+02 1.68000e+03 4.28000e+02]
  [2.55000e+02 1.08500e+03 2.72850e+02]]]
[[[-17.   -70.   -10.6 ]
  [ -7.   -59.7   -0.69]]

 [[  3.   -49.98   9.4 ]
  [ 13.   -39.    19.6 ]]

 [[ 23.4  -46.    29.3 ]
  [ -2.   -54.5   14.8 ]]]
[ 0.  0. 30. 24. 15.]


In [88]:
#Using `Series`, create a `DataFrame` that looks like this:

#    | Ingredients | Quantity | Unit |
#    |----|----|----|
#    | Flour | 4 | cups |
#    | Milk | 1 | cup |
#    | Eggs | 2 | large |
#    | Spam | 1 | can |

#    Name: Dinner, dtype: object



import pandas as pd

Ingredients = pd.Series(["Flour", "Milk", "Eggs", "Spam"], name="Ingredients")
Quantity = pd.Series(["4", "1", "2", "1"], name ="Quantity")
Unit = pd.Series(["cups", "cup", "large", "can"], name="Unit")

Dinner = pd.concat([Ingredients, Quantity, Unit], axis=1)


print(Dinner)





  Ingredients Quantity   Unit
0       Flour        4   cups
1        Milk        1    cup
2        Eggs        2  large
3        Spam        1    can


In [24]:
# Take this data and create a DataFrame named studentData
import pandas as pd

info =    {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
         'Height': [5.1, 6.2, 5.1, 5.2],
         'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
         'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
         'Age': [21, 23, 24, 21],
         'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
         'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
     }
 
studentData = pd.DataFrame(info)


# Add a new column to the DataFrame with the following deserts:
#         ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

deserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
studentData["deserts"] = deserts

# Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"
studentData.sort_values(by = ["Name", "address"], inplace=True)

# Save this `DataFrame` here below to disc as a `.CSV` file with the name `cows_and_goats.csv`:
studentData.to_csv("cows_and_goats.csv")

In [26]:
import pandas as pd

# (A) Using Pandas, make your own .CSV file with data on vegetables and save it. 
info = {'Vegetable': ['Carrot', 'Broccoli', 'Peas', 'Tomato', 'Onion'], 'Color': ['Orange', 'Green', 'Green', 'Red', 'White']}
veggies = pd.DataFrame(info)
veggies.to_csv('Vegetables.csv')


# (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.
veggiesnew = pd.read_csv('Vegetables.csv', delimiter=",", index_col=0)
veggiesnew.sort_values(by = ["Vegetable"], inplace=True)
display(veggiesnew.drop_duplicates(subset="Color", inplace=True))
veggiesnew.to_csv('Cleaned_Vegetables.csv')


None

<div><img src="https://raw.githubusercontent.com/natep514/Homework/main/Images/savvy%20coders%20logo.jpg" style="height:35px;object-fit:cover;"></div>