___
# 5. Python Homework
___

1. What does Pandas stand for?
    * Python Data Analysis Library
2. What are the 2 collections used in Pandas?
    * Series and Dataframes
3. Name 4 things Pandas can do for us.
    * Data Cleaning, Data Fill, Loading and Saving Data, and Data Inspection
4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?
    * `inplace=True`
5. What is a CSV
    * Comma Seperated Value
6. When cleaning data what values do we not like in our data?
    * Null


In [42]:
# Concatenate these 3 arrays into a new array named 'newArray'...
import numpy as np

ax = np.array([[25, 16]])
ay = np.array([[11, 2], [13, 4]])
az = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((ax, ay, az))

# Sort 'newArray' in order into 'sortedArray'
sortedArray = np.sort(newArray)

# Reshape the 'sortedArray' array, into a new array called 'reshapedArray', 
# so it has 2 dimensions with a size of 2, 3.
reshapedArray = np.reshape(sortedArray,(2, 2, 3))
print(reshapedArray)

# Unpack the array tuples from the above 'reshapedArray'  into 4 well named variables. 
# Print the 4 variables.
a, b= reshapedArray
a0, a1 = a
b0, b1 = b
print(a0, a1, b0, b1)

# Combined and sort the following arrays into one called 'comboArray' ...
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.sort(np.concatenate((one, two, three)))

# Take 'comboArray' and perform the following slicing activities:
# print sec1 - the 2nd element
print(comboArray[1])
# print sec2 - all elements from the 3rd element to the last
print(comboArray[2:])
# print sec3 - all elements from the 4th to the 14th elements
print(comboArray[3:15])
# print sec4 - the last 6 elements
print(comboArray[-6:])
# print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
print(comboArray[:-10])    
# print sec6 - from #20 every even element to the end
print(comboArray[20::2])
# print sec7 - from the last element moving forward, every 5th element.
print(comboArray[-1::-5])

[[[16 25  2]
  [11  4 13]]

 [[ 7 81  5]
  [ 6 11 12]]]
[16 25  2] [11  4 13] [ 7 81  5] [ 6 11 12]
1
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14 15 16]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[24 26]
[27 22 15 10  3]


In [47]:
#Using simple math operations, broadcast the addition `(+)`, division `(/)`, and multiplication `(*)` operations for these 2 arrays --


a1 = np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
       [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

a2 = np.array([[17.0, 70.0, 10.7]])


# Use the NumPy Arithmetic functions to do the subtraction of the above two arrays in point #7.
print(a1 - a2)

# Using modulo find all elements that are divisible by 3 from the multi-dimensional array under point #7 above.
print(a1 % 3)
print(np.mod(a1, 3))

[[[-17.   -70.   -10.6 ]
  [ -7.   -59.7   -0.69]]

 [[  3.   -49.98   9.4 ]
  [ 13.   -39.    19.6 ]]

 [[ 23.4  -46.    29.3 ]
  [ -2.   -54.5   14.8 ]]]
[[[0.   0.   0.1 ]
  [1.   1.3  1.01]]

 [[2.   2.02 2.1 ]
  [0.   1.   0.3 ]]

 [[1.4  0.   1.  ]
  [0.   0.5  1.5 ]]]
[[[0.   0.   0.1 ]
  [1.   1.3  1.01]]

 [[2.   2.02 2.1 ]
  [0.   1.   0.3 ]]

 [[1.4  0.   1.  ]
  [0.   0.5  1.5 ]]]


In [75]:
#Using `Series`, create a `DataFrame` that looks like this:

#    | Ingredients | Quantity | Unit |
#    |----|----|----|
#    | Flour | 4 | cups |
#    | Milk | 1 | cup |
#    | Eggs | 2 | large |
#    | Spam | 1 | can |

#    Name: Dinner, dtype: object



import pandas as pd

Ingredients = pd.Series(["Flour", "Milk", "Eggs", "Spam"], name="Ingredients")
Quantity = pd.Series([4, 1, 2, 1], name ="Quantity")
Unit = pd.Series(["cups", "cup", "large", "can"], name="Unit")

Dinner = pd.concat([Ingredients, Quantity, Unit], axis=1)

print(Dinner)





  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Ingredients  4 non-null      object
 1   Quantity     4 non-null      int64 
 2   Unit         4 non-null      object
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes


In [80]:
# Take this data and create a DataFrame named studentData
import pandas as pd

info =    {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
         'Height': [5.1, 6.2, 5.1, 5.2],
         'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
         'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
         'Age': [21, 23, 24, 21],
         'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
         'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
     }
 
studentData = pd.DataFrame(info)


# Add a new column to the DataFrame with the following deserts:
#         ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

deserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
studentData["deserts"] = deserts

# Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"
studentData.sort_values(by = ["Name", "address"], inplace=True)

# Save this `DataFrame` here below to disc as a `.CSV` file with the name `cows_and_goats.csv`:
studentData.to_csv("cows_and_goats.csv")

In [ ]:
# (A) Using Pandas, make your own .CSV file with data on vegetables and save it. 
# (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.
